version: '3.8'

services:
  brain-mapping-eeg:
    build: .
    ports:
      - "9999:9999"
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    environment:
      - FLASK_ENV=production
      - FLASK_DEBUG=false
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - brain-mapping-eeg
    restart: unless-stopped
